name: checking for edge updates
on:
  push:
    branches:
      - main
  schedule:
    - cron: '22 3 * * *'

jobs:
  run:
    name: check update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install edgeupdate-provision
        run: wget https://github.com/42wim/edgeupdate-provision/releases/download/v0.1.5/edgeupdate-provision && chmod 755 edgeupdate-provision

      - name: Checkout repo gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: public

      - name: check update
        run: cd public && ../edgeupdate-provision

      - name: commit
        run: |
          cd public &&
          git config --global push.default matching &&
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" &&
          git config --global user.name "github-actions[bot]" &&
          git add * && git commit -m "Automatic update" && git push
